apiVersion: v1
kind: Pod
metadata:
  name: iperf3-client
  labels:
    app: iperf3-client
spec:
  nodeName: worker1
  containers:
  - name: iperf3
    image: networkstatic/iperf3
    command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server-w1
  labels:
    app: iperf3-server
spec:
  nodeName: worker1
  containers:
  - name: iperf3
    image: networkstatic/iperf3
    args: ["-s"]
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server-w2
  labels:
    app: iperf3-server
spec:
  nodeName: worker2
  containers:
  - name: iperf3
    image: networkstatic/iperf3
    args: ["-s"]
